import type { MetadataRoute } from "next";
import monsIndex from "@/data/mons/index.json";
import { getEventsIndex } from "@/lib/event-pages";
import { getAllReports, getReportFormats } from "@/lib/reports";

const SITE_URL = "https://www.pokemcp.com";

interface MonsFormatIndex {
    dataThrough: string;
    ids: string[];
}

/**
 * Generated sitemap (replaces the old hand-maintained public/sitemap.xml).
 * Sources: the reports manifest and the per-Pokémon data index, both of which
 * are regenerated by scripts/generate-reports.ts when monthly stats land — so
 * lastModified always reflects the data, not the deploy.
 */
export default function sitemap(): MetadataRoute.Sitemap {
    const reports = getAllReports();
    const newestModified = reports[0]?.dateModified ?? "2026-06-10";

    const staticPages: MetadataRoute.Sitemap = [
        {
            url: SITE_URL,
            lastModified: newestModified,
            changeFrequency: "weekly",
            priority: 1.0,
        },
        {
            url: `${SITE_URL}/reports`,
            lastModified: newestModified,
            changeFrequency: "monthly",
            priority: 0.9,
        },
        {
            url: `${SITE_URL}/prep/new`,
            lastModified: newestModified,
            changeFrequency: "weekly",
            priority: 0.9,
        },
        {
            url: `${SITE_URL}/build`,
            lastModified: newestModified,
            changeFrequency: "monthly",
            priority: 0.7,
        },
        {
            url: `${SITE_URL}/privacy`,
            lastModified: newestModified,
            changeFrequency: "yearly",
            priority: 0.3,
        },
    ];

    const latestPages: MetadataRoute.Sitemap = getReportFormats().map((format) => {
        const latest = reports.find((report) => report.slug === format.slug);
        return {
            url: `${SITE_URL}/reports/${format.slug}`,
            lastModified: latest?.dateModified,
            changeFrequency: "monthly",
            priority: 0.9,
        };
    });

    const monthlyPages: MetadataRoute.Sitemap = reports.map((report) => ({
        url: `${SITE_URL}/reports/${report.slug}/${report.month}`,
        lastModified: report.dateModified,
        changeFrequency: "yearly",
        priority: 0.7,
    }));

    const monPages: MetadataRoute.Sitemap = Object.entries(
        monsIndex as Record<string, MonsFormatIndex>,
    ).flatMap(([slug, formatIndex]) =>
        formatIndex.ids.map((id) => ({
            url: `${SITE_URL}/pokemon/${id}/${slug}`,
            lastModified: `${formatIndex.dataThrough}-01`,
            changeFrequency: "monthly" as const,
            priority: 0.6,
        })),
    );

    const eventPages: MetadataRoute.Sitemap = Object.entries(getEventsIndex()).flatMap(
        ([, events]) =>
            events.map((event) => ({
                url: `${SITE_URL}/events/${event.slug}`,
                lastModified: event.date.slice(0, 10),
                changeFrequency: "yearly" as const,
                priority: 0.6,
            })),
    );

    return [...staticPages, ...latestPages, ...monthlyPages, ...monPages, ...eventPages];
}
