/**
 * Script to fetch and cache Smogon usage statistics
 * Run this periodically to update cached data
 *
 * VGC/doubles formats are loaded dynamically from src/discovered-formats.json
 * (generated by scripts/discover-formats.ts). Falls back to a hardcoded list
 * if the discovery file doesn't exist yet.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { Statistics } from "smogon";
import { listRegulationStatsFormats } from "../src/regulations/registry.js";
import { shouldFailRun } from "./lib/stats-run-policy.js";

// Singles formats (stable, rarely change)
const SINGLES_FORMATS = [
    // Gen 9 Singles
    "gen9ou",
    "gen9ubers",
    "gen9uu",
    "gen9ru",
    "gen9nu",
    "gen9pu",
    "gen9lc",
    // Gen 8 Singles
    "gen8ou",
    "gen8ubers",
    "gen8uu",
    "gen8ru",
    "gen8nu",
    "gen8lc",
    // Gen 7 Singles
    "gen7ou",
    "gen7ubers",
    "gen7uu",
    "gen7ru",
    "gen7nu",
    "gen7lc",
];

// Hardcoded fallback for VGC/doubles if discovery hasn't run
const FALLBACK_VGC_FORMATS = [
    "gen9vgc2026regf",
    "gen9vgc2026regfbo3",
    "gen9vgc2025regi",
    "gen9vgc2024regh",
    "gen9doublesou",
];

/**
 * Load VGC/doubles formats from discovery file, falling back to hardcoded list
 */
function getVGCFormats(): string[] {
    try {
        const discoveryPath = join(process.cwd(), "src", "discovered-formats.json");
        const discovered = JSON.parse(readFileSync(discoveryPath, "utf-8"));
        const formats = [...(discovered.vgcFormats || []), ...(discovered.doublesFormats || [])];
        if (formats.length > 0) {
            console.log(
                `Loaded ${formats.length} VGC/doubles formats from discovery (${discovered.sourceMonth})`,
            );
            return formats;
        }
    } catch {
        // Discovery file doesn't exist yet
    }
    console.log("Using hardcoded VGC/doubles format list (run discover-formats first for auto)");
    return FALLBACK_VGC_FORMATS;
}

// Champions (and any future regulation) stats formats, sourced from the
// regulation registry's showdownFormatId fields. Smogon publishes these under
// a `gen9champions…` prefix that doesn't match the VGC/doubles discovery
// patterns, so we pull them explicitly from the single source of truth.
const REGULATION_FORMATS = listRegulationStatsFormats();

// Dedupe so a regulation that mirrors an already-listed format isn't fetched twice.
const FORMATS = [...new Set([...SINGLES_FORMATS, ...getVGCFormats(), ...REGULATION_FORMATS])];
const CACHE_DIR = join(process.cwd(), "src", "cached-stats");

/**
 * Resolve the latest stats month from Smogon's live directory listing.
 *
 * The smogon package's `Statistics.latestDate()` reads a `latest.json` table
 * bundled at publish time, which lags several months behind the live data and
 * is missing brand-new formats entirely (e.g. the `gen9champions…` Champions
 * formats). We resolve the live month once per run and prefer it; the bundled
 * table is only a per-format fallback for formats no longer published in the
 * latest month (e.g. a rotated-out VGC regulation). Cached after first call.
 */
let liveLatestMonth: string | null | undefined;
async function getLiveLatestMonth(): Promise<string | null> {
    if (liveLatestMonth !== undefined) return liveLatestMonth;
    try {
        const response = await fetch(Statistics.URL);
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        liveLatestMonth = Statistics.latest(await response.text()) || null;
        if (liveLatestMonth) console.log(`Live latest stats month: ${liveLatestMonth}\n`);
    } catch (error) {
        console.warn("Could not resolve live latest month, using bundled latestDate:", error);
        liveLatestMonth = null;
    }
    return liveLatestMonth;
}

async function fetchFormatStats(format: string) {
    console.log(`Fetching stats for ${format}...`);

    try {
        // Prefer the live latest month; the chaos report uses the package's
        // default weighting (`Statistics.url(..., true, "chaos")`), e.g.
        // gen9championsvgc2026regma-1630.json. A 404 means the format isn't
        // published in the latest month, so we fall back below.
        const liveMonth = await getLiveLatestMonth();
        if (liveMonth) {
            const liveUrl = Statistics.url(liveMonth, format, true, "chaos");
            const liveResponse = await fetch(liveUrl);
            if (liveResponse.ok) {
                const stats = Statistics.process(await liveResponse.text());
                console.log(
                    `✓ Fetched ${format} @ ${liveMonth} (${Object.keys(stats.data).length} Pokemon)`,
                );
                return { format, date: liveMonth, stats };
            }
        }

        // Fallback: the bundled latest.json (older, but covers formats no
        // longer present in the latest live month).
        const latest = await Statistics.latestDate(format);
        if (!latest) {
            console.warn(`No stats found for ${format}`);
            return null;
        }

        const url = Statistics.url(latest.date, format, true, "chaos");
        const response = await fetch(url);

        if (!response.ok) {
            throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }

        const stats = Statistics.process(await response.text());

        console.log(
            `✓ Fetched ${format} @ ${latest.date} (${Object.keys(stats.data).length} Pokemon) [fallback]`,
        );
        return { format, date: latest.date, stats };
    } catch (error) {
        console.error(`✗ Error fetching ${format}:`, error);
        return null;
    }
}

// Delay helper to be polite to Smogon's servers
const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

async function main() {
    console.log("Fetching Smogon usage statistics...\n");
    console.log("(Rate limited: 2 second delay between requests)\n");
    if (REGULATION_FORMATS.length > 0) {
        console.log(`Regulation stats formats: ${REGULATION_FORMATS.join(", ")}\n`);
    }

    // Create cache directory
    mkdirSync(CACHE_DIR, { recursive: true });

    // Fetch formats sequentially with delay to avoid hammering Smogon
    const results: Awaited<ReturnType<typeof fetchFormatStats>>[] = [];
    const failedFormats: string[] = [];
    for (const format of FORMATS) {
        const result = await fetchFormatStats(format);
        results.push(result);
        if (!result) {
            failedFormats.push(format);
        }
        // Wait 2 seconds between requests to be polite
        if (FORMATS.indexOf(format) < FORMATS.length - 1) {
            await delay(2000);
        }
    }

    // Save each format's data
    for (const result of results) {
        if (result) {
            const filename = join(CACHE_DIR, `${result.format}.json`);
            writeFileSync(
                filename,
                JSON.stringify(
                    {
                        format: result.format,
                        fetchedAt: new Date().toISOString(),
                        date: result.date,
                        data: result.stats,
                    },
                    null,
                    2,
                ),
            );
            console.log(`Saved ${result.format} to cache`);
        }
    }

    // Summary + failure policy: a failed run must LOOK failed. Zero successes
    // (full Smogon outage) or a majority of failures exits non-zero so the
    // workflow step goes red instead of re-uploading stale cache as fresh.
    // A minority of failures (e.g. one format lagging on Smogon's side) is
    // logged loudly but does not fail the run.
    const fetchedCount = FORMATS.length - failedFormats.length;
    console.log(`\nFetch summary: ${fetchedCount} fetched, ${failedFormats.length} failed`);
    if (failedFormats.length > 0) {
        console.error(`✗ Failed formats: ${failedFormats.join(", ")}`);
    }

    if (shouldFailRun(fetchedCount, failedFormats.length)) {
        console.error(
            "\n✗ Fetch failed: zero formats succeeded or a majority failed. " +
                "Smogon may be down — refusing to report success.",
        );
        process.exitCode = 1;
    } else if (failedFormats.length > 0) {
        console.warn(
            "\n⚠ Cache updated, but some formats failed (see above). " +
                "Check whether Smogon is lagging on those formats this month.",
        );
    } else {
        console.log("\n✓ Cache updated successfully!");
    }
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
