/**
 * Generates pokemon-data-generated.ts from the canonical pokedex data.
 * Run with: npm run generate-pokemon-data
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { Pokedex } from "../src/data/pokedex.js";

const OUTPUT_PATH = join(__dirname, "../apps/teambuilder/src/lib/data/pokemon-data-generated.ts");

type PokemonType =
    | "Normal"
    | "Fire"
    | "Water"
    | "Electric"
    | "Grass"
    | "Ice"
    | "Fighting"
    | "Poison"
    | "Ground"
    | "Flying"
    | "Psychic"
    | "Bug"
    | "Rock"
    | "Ghost"
    | "Dragon"
    | "Dark"
    | "Steel"
    | "Fairy";

const VALID_TYPES = new Set<string>([
    "Normal",
    "Fire",
    "Water",
    "Electric",
    "Grass",
    "Ice",
    "Fighting",
    "Poison",
    "Ground",
    "Flying",
    "Psychic",
    "Bug",
    "Rock",
    "Ghost",
    "Dragon",
    "Dark",
    "Steel",
    "Fairy",
]);

interface BaseStats {
    hp: number;
    atk: number;
    def: number;
    spa: number;
    spd: number;
    spe: number;
}

/**
 * Generate name variants for a Pokemon display name.
 * E.g. "Great Tusk" → ["greattusk", "great-tusk", "great tusk"]
 * E.g. "Landorus-Therian" → ["landorustherian", "landorus-therian"]
 */
function getNameVariants(name: string): string[] {
    const lower = name.toLowerCase();
    const variants = new Set<string>();

    // No special chars (pokedex key style): "greattusk"
    variants.add(lower.replace(/[^a-z0-9]/g, ""));

    // Keep hyphens: "landorus-therian", "great-tusk"
    const hyphenated = lower.replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
    variants.add(hyphenated);

    // Spaces instead of hyphens: "great tusk"
    const spaced = lower.replace(/-/g, " ").replace(/[^a-z0-9 ]/g, "");
    if (spaced.includes(" ")) {
        variants.add(spaced);
    }

    return [...variants];
}

function generate() {
    const typeEntries: Record<string, PokemonType[]> = {};
    const statsEntries: Record<string, BaseStats> = {};

    for (const [_key, entry] of Object.entries(Pokedex)) {
        const pokemon = entry as {
            name: string;
            types?: string[];
            baseStats?: {
                hp: number;
                atk: number;
                def: number;
                spa: number;
                spd: number;
                spe: number;
            };
        };

        // Skip entries without types or base stats
        if (!pokemon.types || !pokemon.baseStats) continue;

        // Validate types
        const types = pokemon.types.filter((t) => VALID_TYPES.has(t)) as PokemonType[];
        if (types.length === 0) continue;

        const stats: BaseStats = {
            hp: pokemon.baseStats.hp,
            atk: pokemon.baseStats.atk,
            def: pokemon.baseStats.def,
            spa: pokemon.baseStats.spa,
            spd: pokemon.baseStats.spd,
            spe: pokemon.baseStats.spe,
        };

        const variants = getNameVariants(pokemon.name);
        for (const variant of variants) {
            typeEntries[variant] = types;
            statsEntries[variant] = stats;
        }
    }

    const typesJson = JSON.stringify(typeEntries, null, 4);
    const statsJson = JSON.stringify(statsEntries, null, 4);

    const output = `// Auto-generated by scripts/generate-pokemon-types.ts — do not edit manually
// Re-generate with: npm run generate-pokemon-data

type PokemonType =
    | "Normal" | "Fire" | "Water" | "Electric" | "Grass" | "Ice"
    | "Fighting" | "Poison" | "Ground" | "Flying" | "Psychic" | "Bug"
    | "Rock" | "Ghost" | "Dragon" | "Dark" | "Steel" | "Fairy";

interface BaseStats {
    hp: number;
    atk: number;
    def: number;
    spa: number;
    spd: number;
    spe: number;
}

export const POKEMON_TYPES: Record<string, PokemonType[]> = ${typesJson};

export const POKEMON_BASE_STATS: Record<string, BaseStats> = ${statsJson};
`;

    writeFileSync(OUTPUT_PATH, output, "utf-8");

    const typeCount = Object.keys(typeEntries).length;
    const statsCount = Object.keys(statsEntries).length;
    console.log(
        `Generated ${OUTPUT_PATH}\n  ${typeCount} type entries, ${statsCount} stats entries`,
    );
}

generate();
