/**
 * Regenerate the autogenerated tool-reference tables in README.md and
 * apps/docs/content/tools.mdx from the live tool registry
 * (src/tool-registry.ts), so the published parameter docs can't silently
 * drift from the actual MCP tool surface.
 *
 * Introspects each tool's Zod schema (string/number/boolean/enum/array,
 * optional/default) to build a "name (type, required/optional) — description"
 * fragment per parameter, using the same `.describe()` text authored in the
 * registry. Anything more exotic than the handled cases falls back to
 * "object" rather than throwing, since this is a docs helper, not a schema
 * validator.
 *
 * Only the content between these marker pairs is touched — everything else
 * in both files is hand-written prose and is left alone:
 *   README.md:              <!-- AUTOGEN:TOOLS:BEGIN -->  ...  <!-- AUTOGEN:TOOLS:END -->
 *   apps/docs/content/tools.mdx:  {/* AUTOGEN:TOOLS:BEGIN *\/}  ...  {/* AUTOGEN:TOOLS:END *\/}
 *
 * Usage: bun run generate-tool-docs
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { z } from "zod";
import { TOOL_REGISTRY } from "../src/tool-registry.js";

const ROOT = process.cwd();
const README_PATH = join(ROOT, "README.md");
const TOOLS_MDX_PATH = join(ROOT, "apps/docs/content/tools.mdx");

const README_BEGIN = "<!-- AUTOGEN:TOOLS:BEGIN -->";
const README_END = "<!-- AUTOGEN:TOOLS:END -->";
const MDX_BEGIN = "{/* AUTOGEN:TOOLS:BEGIN */}";
const MDX_END = "{/* AUTOGEN:TOOLS:END */}";

interface ParamInfo {
    name: string;
    type: "string" | "number" | "boolean" | "enum" | "array" | "object";
    required: boolean;
    description?: string;
    enumValues?: string[];
}

/**
 * Walk a Zod schema, unwrapping ZodOptional/ZodDefault wrappers to determine
 * whether the field is required and to find the base type. Descriptions are
 * taken from the outermost schema that has one, matching this codebase's
 * style of calling `.describe()` after `.optional()`.
 */
function introspectParam(name: string, schema: z.ZodTypeAny): ParamInfo {
    let required = true;
    let description = schema.description;
    // Zod's internal `_def` shape isn't part of the public type surface we can
    // narrow generically across ZodOptional/ZodDefault/ZodEnum/etc., so walk
    // it dynamically (as `any`) rather than fighting the type system for a docs script.
    // (noExplicitAny is off repo-wide, so no suppression comment is needed here.)
    let current: any = schema;

    while (current?._def?.typeName === "ZodOptional" || current?._def?.typeName === "ZodDefault") {
        required = false;
        current = current._def.innerType;
        if (!description) description = current.description;
    }

    const typeName = current?._def?.typeName;
    switch (typeName) {
        case "ZodString":
            return { name, type: "string", required, description };
        case "ZodNumber":
            return { name, type: "number", required, description };
        case "ZodBoolean":
            return { name, type: "boolean", required, description };
        case "ZodEnum":
            return {
                name,
                type: "enum",
                required,
                description,
                enumValues: current._def.values as string[],
            };
        case "ZodArray":
            return { name, type: "array", required, description };
        case "ZodObject":
            return { name, type: "object", required, description };
        default:
            // Fallback for anything not handled above (unions, records, etc.)
            return { name, type: "object", required, description };
    }
}

function renderParam(p: ParamInfo): string {
    const reqWord = p.required ? "required" : "optional";
    const typeLabel =
        p.type === "enum" && p.enumValues
            ? `enum: ${p.enumValues.map((v) => `\`${v}\``).join(", ")}, ${reqWord}`
            : `${p.type}, ${reqWord}`;
    const desc = p.description ? ` — ${p.description}` : "";
    return `\`${p.name}\` (${typeLabel})${desc}`;
}

function toolParams(schema: Record<string, z.ZodTypeAny>): ParamInfo[] {
    return Object.entries(schema).map(([name, s]) => introspectParam(name, s));
}

function buildToolsMdxTable(): string {
    const rows = TOOL_REGISTRY.map((tool) => {
        const params = toolParams(tool.schema).map(renderParam).join("; ");
        return `| \`${tool.name}\` | ${params} | ${tool.description} |`;
    });
    return ["| Tool | Parameters | Description |", "|---|---|---|", ...rows].join("\n");
}

function buildReadmeTable(): string {
    const rows = TOOL_REGISTRY.map((tool) => `| \`${tool.name}\` | ${tool.description} |`);
    return ["| Tool | Description |", "|------|-------------|", ...rows].join("\n");
}

function replaceBetweenMarkers(
    content: string,
    beginMarker: string,
    endMarker: string,
    replacement: string,
): string {
    const beginIdx = content.indexOf(beginMarker);
    const endIdx = content.indexOf(endMarker);
    if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
        throw new Error(`Markers "${beginMarker}" / "${endMarker}" not found (or out of order)`);
    }
    const before = content.slice(0, beginIdx + beginMarker.length);
    const after = content.slice(endIdx);
    return `${before}\n${replacement}\n${after}`;
}

function updateFile(path: string, beginMarker: string, endMarker: string, table: string): boolean {
    const original = readFileSync(path, "utf-8");
    const updated = replaceBetweenMarkers(original, beginMarker, endMarker, table);
    if (updated === original) {
        console.log(`  ${path}: already up to date`);
        return false;
    }
    writeFileSync(path, updated);
    console.log(`  ${path}: updated`);
    return true;
}

function main() {
    console.log(`Regenerating tool docs from ${TOOL_REGISTRY.length} registered tools...\n`);

    const readmeChanged = updateFile(README_PATH, README_BEGIN, README_END, buildReadmeTable());
    const toolsMdxChanged = updateFile(TOOLS_MDX_PATH, MDX_BEGIN, MDX_END, buildToolsMdxTable());

    if (!readmeChanged && !toolsMdxChanged) {
        console.log("\nNo changes — docs already match the tool registry.");
    } else {
        console.log("\nDone. Review the diff before committing.");
    }
}

main();
